### ISSUE TITLE
There is no error message when User create Account without selecting "Admin" or "Tester" radio buttons;

### ISSUE THREAD

**Issue by HannaStar** [igor-starostenko/report_factory-web#2]
"REPORT FACTORY" 
VERSION: Beta-1

TITLE: There is no error message when User create Account without selecting "Admin" or "Tester" radio buttons

SEVERITY: Critical
PRIORITY: Medium
ENVIRONMENT: Macbook Air OS High Sierra Ver. 10.13.3
BROWSER: GoogleChrome  Version 64.0.3282.167 

STEPS:
1. Open : http://localhost:3001/;
2. Push  "Login" button;
3. Enter valid data (email and password) into the fields "User name" and "Password";
4. Navigate to the menu bar at the top of the page  and choose "Users";
5. Choose "Create a user";
6. Enter the valid data into the fields "User name", "Email" "Password";
7. Leave radio buttons "Tester" and "Admin" unselected; 
8. Push "Submit" button;
9. Observe the result;

EXPECTED RESULT:
User receive an error message 

ACTUAL RESULT:
User didn't receive an error message

Data:
User name: Hanna
Email: example@admin.com
Password: Welcome1

![screen shot 2018-02-20 at 4 56 23 pm](https://user-images.githubusercontent.com/36213461/36457482-0b5f8ae2-165f-11e8-8366-5649cdb7fa62.png)

**Comment by igor-starostenko** [comment]
@HannaStar will be fixed in the upcoming update. Thanks!
