### ISSUE TITLE
Previous error message doesn't disappear after User fixed the problem; 

### ISSUE THREAD

**Issue by HannaStar** [igor-starostenko/report_factory-web#5]
## "REPORT FACTORY"

VERSION: Beta-1

## TITLE: Previous error message doesn't disappear after User fixed the problem; 

SEVERITY: Minor
PRIORITY: Low
ENVIRONMENT: Macbook Air OS High Sierra Ver. 10.13.3
BROWSER: GoogleChrome Version 64.0.3282.167

## STEPS:

1. Navigate to "/" route;

6. Click "Create a user";
7. Enter User name ;
8. Enter existing email address;
9. Enter password;
10. Choose "Tester" radio button;
11. Click "Submit";
12. Observe result (Error message: "Email has already been taken" ):
13. Enter invalid email address;
14. Observe result ( Error messages: "Email is not valid", "Email has already been taken"):

## ACTUAL RESULT:

Previous error message  disappear after User fixed the problem; 

## EXPECTED RESULT:

Previous error message doesn't disappear after User fixed the problem; 

Precondition:
User logged in .
Email: admin@admin.com
Password: Welcome1

Data:
User name: Hanna2
Email: @admin.com
Password: Welcome1
![screen shot 2018-02-21 at 2 58 13 pm](https://user-images.githubusercontent.com/36213461/36510384-b0192e86-1717-11e8-9df2-476430501689.png)

**Comment by igor-starostenko** [comment]
```
